## Latihan TensorFLow

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tfs = tf.InteractiveSession()

In [3]:
hello = tf.constant("Hello TensorFlow!!")

In [4]:
print(tfs.run(hello))

b'Hello TensorFlow!!'


## Constant

In [5]:
c1 = tf.constant(5, name='x')
c2 = tf.constant(6.0, name='y')
c3 = tf.constant(7.0, tf.float32, name='z')

In [6]:
print('c1 (x): ',c1)
print('c2 (y): ',c2)
print('c3 (z): ',c3)

c1 (x):  Tensor("x:0", shape=(), dtype=int32)
c2 (y):  Tensor("y:0", shape=(), dtype=float32)
c3 (z):  Tensor("z:0", shape=(), dtype=float32)


In [7]:
tfs.run([c1, c2])

[5, 6.0]

In [8]:
tfs.run([c1, c2, c3])

[5, 6.0, 7.0]

In [9]:
tfs.run([c3])

[7.0]

# Operations

In [10]:
op1 = tf.add(c2, c3)
tfs.run(op1)

13.0

In [11]:
# Diffrent datatype cant be proceed
#op1 = tf.add(c1*1.0, c3)
#tfs.run(op1)
op2 = tf.multiply(c2, c3)
tfs.run(op2)

42.0

In [12]:
tfs.run(tf.divide(c2, c3))

0.85714287

In [13]:
tfs.run(tf.subtract(c3, c2))

1.0

In [14]:
# Perkalian skalar dengan tensor (Constant disini)
tfs.run(tf.scalar_mul(3, c1))

15

In [15]:
tfs.run(tf.mod(10, 9))

1

# Placeholder

In [16]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print(p1)

Tensor("Placeholder:0", dtype=float32)


In [17]:
p2

<tf.Tensor 'Placeholder_1:0' shape=<unknown> dtype=float32>

In [18]:
op4 = p1 * p2
tfs.run(op4, {p1:2.0, p2:4.0})

8.0

In [19]:
tfs.run(op4, feed_dict={p1:8.0, p2:4.0})

32.0

In [20]:
tfs.run(op4, feed_dict={p1:[8.0, 3.0, 2.0], p2:[4.0, 3.3, 3.9]})

array([32. ,  9.9,  7.8], dtype=float32)

# Creating tensors from Python objects

In [26]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)
tf_t

<tf.Tensor 'Const_3:0' shape=() dtype=float64>

In [22]:
tfs.run(tf_t)

5.0

In [23]:
a1dim = np.array([1, 2, 3, 4, 5.99])
a1dim.shape

(5,)

In [27]:
tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)
tf_t

<tf.Tensor 'Const_4:0' shape=(5,) dtype=float64>

In [28]:
tf_t[0]

<tf.Tensor 'strided_slice:0' shape=() dtype=float64>

In [29]:
tf_t[2]

<tf.Tensor 'strided_slice_1:0' shape=() dtype=float64>

In [30]:
tfs.run(tf_t)

array([1.  , 2.  , 3.  , 4.  , 5.99])

In [31]:
a2dim = np.array([(1,2,3,4,5.99),
                 (2,3,4,5,6.99),
                 (3,4,5,6,7.99)
                 ])
a2dim.shape

(3, 5)

In [33]:
tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)
tf_t

<tf.Tensor 'Const_5:0' shape=(3, 5) dtype=float64>

In [34]:
tf_t[0][0]

<tf.Tensor 'strided_slice_3:0' shape=() dtype=float64>

In [35]:
tf_t[1][2]

<tf.Tensor 'strided_slice_5:0' shape=() dtype=float64>

In [36]:
tfs.run(tf_t)

array([[1.  , 2.  , 3.  , 4.  , 5.99],
       [2.  , 3.  , 4.  , 5.  , 6.99],
       [3.  , 4.  , 5.  , 6.  , 7.99]])

In [43]:
a3dim = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]
                 ])
a3dim.shape

(2, 2, 2)

In [44]:
tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)
tf_t

<tf.Tensor 'Const_6:0' shape=(2, 2, 2) dtype=float64>

In [45]:
tf_t[0][0][0]

<tf.Tensor 'strided_slice_8:0' shape=() dtype=float64>

In [46]:
tf_t[1][1][1]

<tf.Tensor 'strided_slice_11:0' shape=() dtype=float64>

In [47]:
tfs.run(tf_t)

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

# Variables

In [4]:
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)

In [5]:
x = tf.placeholder(tf.float32)

In [6]:
y = w*x + b

In [7]:
w

<tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>

In [9]:
x

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [10]:
b

<tf.Variable 'Variable_2:0' shape=(1,) dtype=float32_ref>

In [11]:
y

<tf.Tensor 'add:0' shape=<unknown> dtype=float32>

In [14]:
tfs.run(w.initializer)

In [15]:
tfs.run(tf.global_variables_initializer())

In [16]:
tfs.run(y, {x: [1, 2, 3, 4]})

array([0.        , 0.3       , 0.6       , 0.90000004], dtype=float32)

# Tensors generated from library functions

In [17]:
a = tf.zeros((100,))
tfs.run(a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

# Populating tensor elements with the same values

In [18]:
one = tf.ones((200,))
tfs.run(one)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [23]:
var = tf.fill([2,3], 9)
tfs.run(var)

array([[9, 9, 9],
       [9, 9, 9]])

# Populating tensor elements with sequences

In [31]:
a = tf.lin_space(1., 102., 10)
tfs.run(a)

array([  1.      ,  12.222222,  23.444445,  34.666668,  45.88889 ,
        57.11111 ,  68.333336,  79.55556 ,  90.77778 , 102.      ],
      dtype=float32)

In [33]:
a = tf.range(1., 50., 3)
tfs.run(a)

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46., 49.], dtype=float32)

# Populating tensor elements with a random distribution

In [42]:
a = tf.random_normal([2, 3], 10, .344345)
tfs.run(a)

array([[ 9.963649,  9.843288, 10.4266  ],
       [ 9.529442, 10.051443, 10.054031]], dtype=float32)

In [52]:
a = tf.random_uniform([2, 3], 9, 20, dtype=tf.int32)
tfs.run(a)

array([[ 9,  9, 17],
       [13, 12, 14]])

In [61]:
w = tf.get_variable(name='w',dtype=tf.float32,initializer=[.3])
b = tf.get_variable(name='b',dtype=tf.float32,initializer=[-.3])

ValueError: Variable w already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Users\Ultimate\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
  File "C:\Users\Ultimate\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\Ultimate\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\Ultimate\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Ultimate\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)


In [59]:
tf.keras

<module 'tensorflow.python.keras.api._v1.keras' from 'C:\\Users\\Ultimate\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\keras\\api\\_v1\\keras\\__init__.py'>

# Data flow graph or computation graph

In [63]:
grap = tf.get_default_graph()

In [66]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b
output = 0
with tf.Session() as tfs:
    # initialize and print the variable y
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})
print(output)

[0.         0.3        0.6        0.90000004]


# Order of execution and lazy loading

# Executing graphs across compute devices - CPU and GPGPU

In [68]:
from tensorflow.python.client import device_lib

In [69]:
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 145189002799772848
]


# Placing graph nodes on specific compute devices

In [4]:
tf.reset_default_graph

<function tensorflow.python.framework.ops.reset_default_graph()>

In [5]:
# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)

In [6]:
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b

In [8]:
config = tf.ConfigProto()
config.log_device_placement=True

In [10]:
with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    tfs.run(y, {x:[1,2,3,4]})

Device mapping:

